package routes

// This selection adapted from a table from httprouter tests by Julien Schmidt

// GithubAPI is a selection of routes from the Github API
// http://developer.github.com/v3/
var GithubAPI = []Route{
	// OAuth Authorizations
	{Method: "GET", Pattern: "/authorizations", Path: "/authorizations"},
	{Method: "GET", Pattern: "/authorizations/{id:\\d+}", Path: "/authorizations/99"},
	{Method: "POST", Pattern: "/authorizations", Path: "/authorizations"},
	{Method: "PUT", Pattern: "/authorizations/clients/{client_id:\\d+}", Path: "/authorizations/clients/99"},
	{Method: "PATCH", Pattern: "/authorizations/{id:\\d+}", Path: "/authorizations/99"},
	{Method: "DELETE", Pattern: "/authorizations/{id:\\d+}", Path: "/authorizations/99"},
	{Method: "GET", Pattern: "/applications/{client_id:\\d+}/tokens/{access_token:\\d+}", Path: "/applications/33/tokens/99"},
	{Method: "DELETE", Pattern: "/applications/{client_id:\\d+}/tokens", Path: "/applications/33/tokens"},
	{Method: "DELETE", Pattern: "/applications/{client_id:\\d+}/tokens/{access_token:\\d+}", Path: "/applications/33/tokens/99"},

	// Activity
	{Method: "GET", Pattern: "/events", Path: "/events"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/events", Path: "/repos/22/33/events"},
	{Method: "GET", Pattern: "/networks/{owner:\\d+}/{repo:\\d+}/events", Path: "/networks/22/33/events"},
	{Method: "GET", Pattern: "/orgs/{org:\\d+}/events", Path: "/orgs/33/events"},
	{Method: "GET", Pattern: "/users/{user:\\d+}/received_events", Path: "/users/33/received_events"},
	{Method: "GET", Pattern: "/users/{user:\\d+}/received_events/public", Path: "/users/33/received_events/public"},
	{Method: "GET", Pattern: "/users/{user:\\d+}/events", Path: "/users/33/events"},
	{Method: "GET", Pattern: "/users/{user:\\d+}/events/public", Path: "/users/33/events/public"},
	{Method: "GET", Pattern: "/users/{user:\\d+}/events/orgs/{org:\\d+}", Path: "/users/33/events/orgs/99"},
	{Method: "GET", Pattern: "/feeds", Path: "/feeds"},
	{Method: "GET", Pattern: "/notifications", Path: "/notifications"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/notifications", Path: "/repos/22/33/notifications"},
	{Method: "PUT", Pattern: "/notifications", Path: "/notifications"},
	{Method: "PUT", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/notifications", Path: "/repos/22/33/notifications"},
	{Method: "GET", Pattern: "/notifications/threads/{id:\\d+}", Path: "/notifications/threads/99"},
	{Method: "PATCH", Pattern: "/notifications/threads/{id:\\d+}", Path: "/notifications/threads/99"},
	{Method: "GET", Pattern: "/notifications/threads/{id:\\d+}/subscription", Path: "/notifications/threads/33/subscription"},
	{Method: "PUT", Pattern: "/notifications/threads/{id:\\d+}/subscription", Path: "/notifications/threads/33/subscription"},
	{Method: "DELETE", Pattern: "/notifications/threads/{id:\\d+}/subscription", Path: "/notifications/threads/33/subscription"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/stargazers", Path: "/repos/22/33/stargazers"},
	{Method: "GET", Pattern: "/users/{user:\\d+}/starred", Path: "/users/33/starred"},
	{Method: "GET", Pattern: "/user/starred", Path: "/user/starred"},
	{Method: "GET", Pattern: "/user/starred/{owner:\\d+}/{repo:\\d+}", Path: "/user/starred/33/99"},
	{Method: "PUT", Pattern: "/user/starred/{owner:\\d+}/{repo:\\d+}", Path: "/user/starred/33/99"},
	{Method: "DELETE", Pattern: "/user/starred/{owner:\\d+}/{repo:\\d+}", Path: "/user/starred/33/99"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/subscribers", Path: "/repos/22/33/subscribers"},
	{Method: "GET", Pattern: "/users/{user:\\d+}/subscriptions", Path: "/users/33/subscriptions"},
	{Method: "GET", Pattern: "/user/subscriptions", Path: "/user/subscriptions"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/subscription", Path: "/repos/22/33/subscription"},
	{Method: "PUT", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/subscription", Path: "/repos/22/33/subscription"},
	{Method: "DELETE", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/subscription", Path: "/repos/22/33/subscription"},
	{Method: "GET", Pattern: "/user/subscriptions/{owner:\\d+}/{repo:\\d+}", Path: "/user/subscriptions/33/99"},
	{Method: "PUT", Pattern: "/user/subscriptions/{owner:\\d+}/{repo:\\d+}", Path: "/user/subscriptions/33/99"},
	{Method: "DELETE", Pattern: "/user/subscriptions/{owner:\\d+}/{repo:\\d+}", Path: "/user/subscriptions/33/99"},

	// Gists
	{Method: "GET", Pattern: "/users/{user:\\d+}/gists", Path: "/users/33/gists"},
	{Method: "GET", Pattern: "/gists", Path: "/gists"},
	{Method: "GET", Pattern: "/gists/public", Path: "/gists/public"},
	{Method: "GET", Pattern: "/gists/starred", Path: "/gists/starred"},
	{Method: "GET", Pattern: "/gists/{id:\\d+}", Path: "/gists/99"},
	{Method: "POST", Pattern: "/gists", Path: "/gists"},
	{Method: "PATCH", Pattern: "/gists/{id:\\d+}", Path: "/gists/99"},
	{Method: "PUT", Pattern: "/gists/{id:\\d+}/star", Path: "/gists/33/star"},
	{Method: "DELETE", Pattern: "/gists/{id:\\d+}/star", Path: "/gists/33/star"},
	{Method: "GET", Pattern: "/gists/{id:\\d+}/star", Path: "/gists/33/star"},
	{Method: "POST", Pattern: "/gists/{id:\\d+}/forks", Path: "/gists/33/forks"},
	{Method: "DELETE", Pattern: "/gists/{id:\\d+}", Path: "/gists/99"},

	// Git Data
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/git/blobs/{sha:\\d+}", Path: "/repos/22/33/git/blobs/99"},
	{Method: "POST", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/git/blobs", Path: "/repos/22/33/git/blobs"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/git/commits/{sha:\\d+}", Path: "/repos/22/33/git/commits/99"},
	{Method: "POST", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/git/commits", Path: "/repos/22/33/git/commits"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/git/refs/*ref", Path: "/repos/22/33/git/refs/*ref"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/git/refs", Path: "/repos/22/33/git/refs"},
	{Method: "POST", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/git/refs", Path: "/repos/22/33/git/refs"},
	{Method: "PATCH", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/git/refs/*ref", Path: "/repos/22/33/git/refs/*ref"},
	{Method: "DELETE", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/git/refs/*ref", Path: "/repos/22/33/git/refs/*ref"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/git/tags/{sha:\\d+}", Path: "/repos/22/33/git/tags/99"},
	{Method: "POST", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/git/tags", Path: "/repos/22/33/git/tags"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/git/trees/{sha:\\d+}", Path: "/repos/22/33/git/trees/99"},
	{Method: "POST", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/git/trees", Path: "/repos/22/33/git/trees"},

	// Issues
	{Method: "GET", Pattern: "/issues", Path: "/issues"},
	{Method: "GET", Pattern: "/user/issues", Path: "/user/issues"},
	{Method: "GET", Pattern: "/orgs/{org:\\d+}/issues", Path: "/orgs/33/issues"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/issues", Path: "/repos/22/33/issues"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/issues/{number:\\d+}", Path: "/repos/22/33/issues/99"},
	{Method: "POST", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/issues", Path: "/repos/22/33/issues"},
	{Method: "PATCH", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/issues/{number:\\d+}", Path: "/repos/22/33/issues/99"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/assignees", Path: "/repos/22/33/assignees"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/assignees/{assignee:\\d+}", Path: "/repos/22/33/assignees/99"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/issues/{number:\\d+}/comments", Path: "/repos/22/22/issues/33/comments"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/issues/comments", Path: "/repos/22/33/issues/comments"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/issues/comments/{id:\\d+}", Path: "/repos/22/33/issues/comments/99"},
	{Method: "POST", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/issues/{number:\\d+}/comments", Path: "/repos/22/22/issues/33/comments"},
	{Method: "PATCH", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/issues/comments/{id:\\d+}", Path: "/repos/22/33/issues/comments/99"},
	{Method: "DELETE", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/issues/comments/{id:\\d+}", Path: "/repos/22/33/issues/comments/99"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/issues/{number:\\d+}/events", Path: "/repos/22/22/issues/33/events"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/issues/events", Path: "/repos/22/33/issues/events"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/issues/events/{id:\\d+}", Path: "/repos/22/33/issues/events/99"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/labels", Path: "/repos/22/33/labels"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/labels/{name:\\d+}", Path: "/repos/22/33/labels/99"},
	{Method: "POST", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/labels", Path: "/repos/22/33/labels"},
	{Method: "PATCH", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/labels/{name:\\d+}", Path: "/repos/22/33/labels/99"},
	{Method: "DELETE", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/labels/{name:\\d+}", Path: "/repos/22/33/labels/99"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/issues/{number:\\d+}/labels", Path: "/repos/22/22/issues/33/labels"},
	{Method: "POST", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/issues/{number:\\d+}/labels", Path: "/repos/22/22/issues/33/labels"},
	{Method: "DELETE", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/issues/{number:\\d+}/labels/{name:\\d+}", Path: "/repos/22/22/issues/33/labels/99"},
	{Method: "PUT", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/issues/{number:\\d+}/labels", Path: "/repos/22/22/issues/33/labels"},
	{Method: "DELETE", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/issues/{number:\\d+}/labels", Path: "/repos/22/22/issues/33/labels"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/milestones/{number:\\d+}/labels", Path: "/repos/22/22/milestones/33/labels"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/milestones", Path: "/repos/22/33/milestones"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/milestones/{number:\\d+}", Path: "/repos/22/33/milestones/99"},
	{Method: "POST", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/milestones", Path: "/repos/22/33/milestones"},
	{Method: "PATCH", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/milestones/{number:\\d+}", Path: "/repos/22/33/milestones/99"},
	{Method: "DELETE", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/milestones/{number:\\d+}", Path: "/repos/22/33/milestones/99"},

	// Miscellaneous
	{Method: "GET", Pattern: "/emojis", Path: "/emojis"},
	{Method: "GET", Pattern: "/gitignore/templates", Path: "/gitignore/templates"},
	{Method: "GET", Pattern: "/gitignore/templates/{name:\\d+}", Path: "/gitignore/templates/99"},
	{Method: "POST", Pattern: "/markdown", Path: "/markdown"},
	{Method: "POST", Pattern: "/markdown/raw", Path: "/markdown/raw"},
	{Method: "GET", Pattern: "/meta", Path: "/meta"},
	{Method: "GET", Pattern: "/rate_limit", Path: "/rate_limit"},

	// Organizations
	{Method: "GET", Pattern: "/users/{user:\\d+}/orgs", Path: "/users/33/orgs"},
	{Method: "GET", Pattern: "/user/orgs", Path: "/user/orgs"},
	{Method: "GET", Pattern: "/orgs/{org:\\d+}", Path: "/orgs/99"},
	{Method: "PATCH", Pattern: "/orgs/{org:\\d+}", Path: "/orgs/99"},
	{Method: "GET", Pattern: "/orgs/{org:\\d+}/members", Path: "/orgs/33/members"},
	{Method: "GET", Pattern: "/orgs/{org:\\d+}/members/{user:\\d+}", Path: "/orgs/33/members/99"},
	{Method: "DELETE", Pattern: "/orgs/{org:\\d+}/members/{user:\\d+}", Path: "/orgs/33/members/99"},
	{Method: "GET", Pattern: "/orgs/{org:\\d+}/public_members", Path: "/orgs/33/public_members"},
	{Method: "GET", Pattern: "/orgs/{org:\\d+}/public_members/{user:\\d+}", Path: "/orgs/33/public_members/99"},
	{Method: "PUT", Pattern: "/orgs/{org:\\d+}/public_members/{user:\\d+}", Path: "/orgs/33/public_members/99"},
	{Method: "DELETE", Pattern: "/orgs/{org:\\d+}/public_members/{user:\\d+}", Path: "/orgs/33/public_members/99"},
	{Method: "GET", Pattern: "/orgs/{org:\\d+}/teams", Path: "/orgs/33/teams"},
	{Method: "GET", Pattern: "/teams/{id:\\d+}", Path: "/teams/99"},
	{Method: "POST", Pattern: "/orgs/{org:\\d+}/teams", Path: "/orgs/33/teams"},
	{Method: "PATCH", Pattern: "/teams/{id:\\d+}", Path: "/teams/99"},
	{Method: "DELETE", Pattern: "/teams/{id:\\d+}", Path: "/teams/99"},
	{Method: "GET", Pattern: "/teams/{id:\\d+}/members", Path: "/teams/33/members"},
	{Method: "GET", Pattern: "/teams/{id:\\d+}/members/{user:\\d+}", Path: "/teams/33/members/99"},
	{Method: "PUT", Pattern: "/teams/{id:\\d+}/members/{user:\\d+}", Path: "/teams/33/members/99"},
	{Method: "DELETE", Pattern: "/teams/{id:\\d+}/members/{user:\\d+}", Path: "/teams/33/members/99"},
	{Method: "GET", Pattern: "/teams/{id:\\d+}/repos", Path: "/teams/33/repos"},
	{Method: "GET", Pattern: "/teams/{id:\\d+}/repos/{owner:\\d+}/{repo:\\d+}", Path: "/teams/22/repos/33/99"},
	{Method: "PUT", Pattern: "/teams/{id:\\d+}/repos/{owner:\\d+}/{repo:\\d+}", Path: "/teams/22/repos/33/99"},
	{Method: "DELETE", Pattern: "/teams/{id:\\d+}/repos/{owner:\\d+}/{repo:\\d+}", Path: "/teams/22/repos/33/99"},
	{Method: "GET", Pattern: "/user/teams", Path: "/user/teams"},

	// Pull Requests
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/pulls", Path: "/repos/22/33/pulls"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/pulls/{number:\\d+}", Path: "/repos/22/33/pulls/99"},
	{Method: "POST", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/pulls", Path: "/repos/22/33/pulls"},
	{Method: "PATCH", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/pulls/{number:\\d+}", Path: "/repos/22/33/pulls/99"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/pulls/{number:\\d+}/commits", Path: "/repos/22/22/pulls/33/commits"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/pulls/{number:\\d+}/files", Path: "/repos/22/22/pulls/33/files"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/pulls/{number:\\d+}/merge", Path: "/repos/22/22/pulls/33/merge"},
	{Method: "PUT", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/pulls/{number:\\d+}/merge", Path: "/repos/22/22/pulls/33/merge"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/pulls/{number:\\d+}/comments", Path: "/repos/22/22/pulls/33/comments"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/pulls/comments", Path: "/repos/22/33/pulls/comments"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/pulls/comments/{number:\\d+}", Path: "/repos/22/33/pulls/comments/99"},
	{Method: "PUT", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/pulls/{number:\\d+}/comments", Path: "/repos/22/22/pulls/33/comments"},
	{Method: "PATCH", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/pulls/comments/{number:\\d+}", Path: "/repos/22/33/pulls/comments/99"},
	{Method: "DELETE", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/pulls/comments/{number:\\d+}", Path: "/repos/22/33/pulls/comments/99"},

	// Repositories
	{Method: "GET", Pattern: "/user/repos", Path: "/user/repos"},
	{Method: "GET", Pattern: "/users/{user:\\d+}/repos", Path: "/users/33/repos"},
	{Method: "GET", Pattern: "/orgs/{org:\\d+}/repos", Path: "/orgs/33/repos"},
	{Method: "GET", Pattern: "/repositories", Path: "/repositories"},
	{Method: "POST", Pattern: "/user/repos", Path: "/user/repos"},
	{Method: "POST", Pattern: "/orgs/{org:\\d+}/repos", Path: "/orgs/33/repos"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}", Path: "/repos/33/99"},
	{Method: "PATCH", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}", Path: "/repos/33/99"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/contributors", Path: "/repos/22/33/contributors"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/languages", Path: "/repos/22/33/languages"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/teams", Path: "/repos/22/33/teams"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/tags", Path: "/repos/22/33/tags"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/branches", Path: "/repos/22/33/branches"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/branches/{branch:\\d+}", Path: "/repos/22/33/branches/99"},
	{Method: "DELETE", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}", Path: "/repos/33/99"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/collaborators", Path: "/repos/22/33/collaborators"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/collaborators/{user:\\d+}", Path: "/repos/22/33/collaborators/99"},
	{Method: "PUT", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/collaborators/{user:\\d+}", Path: "/repos/22/33/collaborators/99"},
	{Method: "DELETE", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/collaborators/{user:\\d+}", Path: "/repos/22/33/collaborators/99"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/comments", Path: "/repos/22/33/comments"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/commits/{sha:\\d+}/comments", Path: "/repos/22/22/commits/33/comments"},
	{Method: "POST", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/commits/{sha:\\d+}/comments", Path: "/repos/22/22/commits/33/comments"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/comments/{id:\\d+}", Path: "/repos/22/33/comments/99"},
	{Method: "PATCH", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/comments/{id:\\d+}", Path: "/repos/22/33/comments/99"},
	{Method: "DELETE", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/comments/{id:\\d+}", Path: "/repos/22/33/comments/99"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/commits", Path: "/repos/22/33/commits"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/commits/{sha:\\d+}", Path: "/repos/22/33/commits/99"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/readme", Path: "/repos/22/33/readme"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/contents/*path", Path: "/repos/22/33/contents/*path"},
	{Method: "PUT", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/contents/*path", Path: "/repos/22/33/contents/*path"},
	{Method: "DELETE", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/contents/*path", Path: "/repos/22/33/contents/*path"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/{archive_format:\\d+}/{ref:\\d+}", Path: "/repos/22/22/33/99"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/keys", Path: "/repos/22/33/keys"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/keys/{id:\\d+}", Path: "/repos/22/33/keys/99"},
	{Method: "POST", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/keys", Path: "/repos/22/33/keys"},
	{Method: "PATCH", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/keys/{id:\\d+}", Path: "/repos/22/33/keys/99"},
	{Method: "DELETE", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/keys/{id:\\d+}", Path: "/repos/22/33/keys/99"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/downloads", Path: "/repos/22/33/downloads"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/downloads/{id:\\d+}", Path: "/repos/22/33/downloads/99"},
	{Method: "DELETE", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/downloads/{id:\\d+}", Path: "/repos/22/33/downloads/99"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/forks", Path: "/repos/22/33/forks"},
	{Method: "POST", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/forks", Path: "/repos/22/33/forks"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/hooks", Path: "/repos/22/33/hooks"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/hooks/{id:\\d+}", Path: "/repos/22/33/hooks/99"},
	{Method: "POST", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/hooks", Path: "/repos/22/33/hooks"},
	{Method: "PATCH", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/hooks/{id:\\d+}", Path: "/repos/22/33/hooks/99"},
	{Method: "POST", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/hooks/{id:\\d+}/tests", Path: "/repos/22/22/hooks/33/tests"},
	{Method: "DELETE", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/hooks/{id:\\d+}", Path: "/repos/22/33/hooks/99"},
	{Method: "POST", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/merges", Path: "/repos/22/33/merges"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/releases", Path: "/repos/22/33/releases"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/releases/{id:\\d+}", Path: "/repos/22/33/releases/99"},
	{Method: "POST", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/releases", Path: "/repos/22/33/releases"},
	{Method: "PATCH", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/releases/{id:\\d+}", Path: "/repos/22/33/releases/99"},
	{Method: "DELETE", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/releases/{id:\\d+}", Path: "/repos/22/33/releases/99"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/releases/{id:\\d+}/assets", Path: "/repos/22/22/releases/33/assets"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/stats/contributors", Path: "/repos/22/33/stats/contributors"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/stats/commit_activity", Path: "/repos/22/33/stats/commit_activity"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/stats/code_frequency", Path: "/repos/22/33/stats/code_frequency"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/stats/participation", Path: "/repos/22/33/stats/participation"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/stats/punch_card", Path: "/repos/22/33/stats/punch_card"},
	{Method: "GET", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/statuses/{ref:\\d+}", Path: "/repos/22/33/statuses/99"},
	{Method: "POST", Pattern: "/repos/{owner:\\d+}/{repo:\\d+}/statuses/{ref:\\d+}", Path: "/repos/22/33/statuses/99"},

	// Search
	{Method: "GET", Pattern: "/search/repositories", Path: "/search/repositories"},
	{Method: "GET", Pattern: "/search/code", Path: "/search/code"},
	{Method: "GET", Pattern: "/search/issues", Path: "/search/issues"},
	{Method: "GET", Pattern: "/search/users", Path: "/search/users"},
	{Method: "GET", Pattern: "/legacy/issues/search/{owner:\\d+}/{repository:\\d+}/{state:\\d+}/{keyword:\\d+}", Path: "/legacy/issues/search/22/22/33/99"},
	{Method: "GET", Pattern: "/legacy/repos/search/{keyword:\\d+}", Path: "/legacy/repos/search/99"},
	{Method: "GET", Pattern: "/legacy/user/search/{keyword:\\d+}", Path: "/legacy/user/search/99"},
	{Method: "GET", Pattern: "/legacy/user/email/{email:\\d+}", Path: "/legacy/user/email/99"},

	// Users
	{Method: "GET", Pattern: "/users/{user:\\d+}", Path: "/users/99"},
	{Method: "GET", Pattern: "/user", Path: "/user"},
	{Method: "PATCH", Pattern: "/user", Path: "/user"},
	{Method: "GET", Pattern: "/users", Path: "/users"},
	{Method: "GET", Pattern: "/user/emails", Path: "/user/emails"},
	{Method: "POST", Pattern: "/user/emails", Path: "/user/emails"},
	{Method: "DELETE", Pattern: "/user/emails", Path: "/user/emails"},
	{Method: "GET", Pattern: "/users/{user:\\d+}/followers", Path: "/users/33/followers"},
	{Method: "GET", Pattern: "/user/followers", Path: "/user/followers"},
	{Method: "GET", Pattern: "/users/{user:\\d+}/following", Path: "/users/33/following"},
	{Method: "GET", Pattern: "/user/following", Path: "/user/following"},
	{Method: "GET", Pattern: "/user/following/{user:\\d+}", Path: "/user/following/99"},
	{Method: "GET", Pattern: "/users/{user:\\d+}/following/{target_user:\\d+}", Path: "/users/33/following/99"},
	{Method: "PUT", Pattern: "/user/following/{user:\\d+}", Path: "/user/following/99"},
	{Method: "DELETE", Pattern: "/user/following/{user:\\d+}", Path: "/user/following/99"},
	{Method: "GET", Pattern: "/users/{user:\\d+}/keys", Path: "/users/33/keys"},
	{Method: "GET", Pattern: "/user/keys", Path: "/user/keys"},
	{Method: "GET", Pattern: "/user/keys/{id:\\d+}", Path: "/user/keys/99"},
	{Method: "POST", Pattern: "/user/keys", Path: "/user/keys"},
	{Method: "PATCH", Pattern: "/user/keys/{id:\\d+}", Path: "/user/keys/99"},
	{Method: "DELETE", Pattern: "/user/keys/{id:\\d+}", Path: "/user/keys/99"},
}
